package dev.nozh.api;

import java.util.List;

/**
 * Immutable action plan generated by Governor.
 * 
 * Contains one or more actions to apply, along with reasoning.
 * 
 * Phase 2: Data structure definition
 * Phase 5: Populated by passive governor
 * Phase 6: Executed by ActionExecutor
 */
public record ActionPlan(
        List<Action> actions,
        String reasoning,
        boolean blocked,
        String blockReason) {

    /**
     * Empty plan (no actions).
     */
    public static ActionPlan empty(String reason) {
        return new ActionPlan(List.of(), reason, false, null);
    }

    /**
     * Blocked plan (actions exist but cannot be applied).
     */
    public static ActionPlan blocked(List<Action> actions, String blockReason) {
        return new ActionPlan(actions, "Blocked", true, blockReason);
    }

    /**
     * Check if plan has actions.
     */
    public boolean hasActions() {
        return !actions.isEmpty();
    }
}
